CREATE SEQUENCE FILM_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE ROUNDS_SEQ START WITH 1 INCREMENT BY 50;

CREATE TABLE Users (
    id INT AUTO_INCREMENT,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE Film(
    id INT AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    rating FLOAT,
    votes INT,
    CONSTRAINT pk_film PRIMARY KEY (id)
);

CREATE TABLE Rounds(
    id INT AUTO_INCREMENT,
    user_id INT NOT NULL,
    film1_id INT NOT NULL,
    film2_id INT NOT NULL,
    points INT,
    CONSTRAINT pk_round PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES Users(id),
    FOREIGN KEY (film1_id) REFERENCES Film(id),
    FOREIGN KEY (film2_id) REFERENCES Film(id)
);
